#!/bin/bash 

set -euo pipefail

# Add support for multiple tags
# https://blog.nathanv.me/posts/docker-hub-multiple-tags/
IFS=',' read -ra tags <<< "$DOCKER_TAG"
tag_params=()
for tag in "${tags[@]}"; do
    tag_params+=('-t' "$DOCKER_REPO:$tag")
done

set -x

# PHP version should be the first tag
PHP_VERSION="${DOCKER_TAG%%,*}"

docker build \
    --build-arg PHP_VERSION="$PHP_VERSION" \
    -f "$DOCKERFILE_PATH" \
    "${tag_params[@]}" .
