#!/bin/sh

set -e

if [ -n "$1" ]; then
    export HEALTH_CHECK_IP="$1"
fi

if [ -n "$2" ]; then
    export HEALTH_CHECK_PORT="$2"
fi

env -i REDIRECT_STATUS=true \
    SCRIPT_NAME=/ping \
    SCRIPT_FILENAME=/ping \
    REQUEST_METHOD=GET \
    cgi-fcgi -bind -connect \
    "${HEALTH_CHECK_IP:-127.0.0.1}:${HEALTH_CHECK_PORT:-9000}" \
    | grep -e pong >/dev/null
